name: Build and deploy mkdocs to github pages
on:
  push:
    branches:
      - main
    paths-ignore:
      - "package.json"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip     # install pip
          python3 -m pip uninstall lxml
          python3 -m pip install lxml
          python3 -m pip install mkdocs==1.4.3            # install mkdocs 
          python3 -m pip install mkdocs-material=9.1.13   # install material theme
          python3 -m pip install https://github.com/bmcorser/fontawesome-markdown/archive/master.zip   # install font-awesome
          python3 -m pip install mkdocs-git-revision-date-plugin # install git revision date
          python3 -m pip install -r requirements.txt
      - name: Build site
        run: mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./site
